# Generated by Django 3.1 on 2020-08-27 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20200827_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_city', to=settings.AUTH_USER_MODEL),
        ),
    ]
